"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory\
$git_branch\
$git_status\
$character
"""

add_newline = false

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style) "
